### ISSUE TITLE
Recomendation

### ISSUE THREAD

**Issue by TotoMC-13** [bestman8/rendering-with-luxcore-in-blender-with-google-colab#1]
You can also directly download the luxcore file on google drive instead of uploading it from your computer

**Comment by bestman8** [comment]
i know but this way it was a bit simpler for me to make it

**Comment by TotoMC-13** [comment]
oh, ok, if you want i can do a pr and add that.

**Comment by bestman8** [comment]
not needed

**Comment by TotoMC-13** [comment]
ok!
